# Generated by Django 4.0.3 on 2022-05-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatistics',
            fields=[
                ('DeviceId', models.AutoField(primary_key=True, serialize=False)),
                ('DeviceNetworkUpLink', models.CharField(max_length=100)),
                ('DeviceNetworkDownLink', models.CharField(max_length=100)),
                ('DeviceUp1', models.CharField(max_length=100)),
                ('DeviceDown1', models.CharField(max_length=100)),
                ('DeviceUp2', models.CharField(max_length=100)),
                ('DeviceDown2', models.CharField(max_length=100)),
                ('DeviceUp3', models.CharField(max_length=100)),
                ('DeviceDown3', models.CharField(max_length=100)),
                ('DeviceUp4', models.CharField(max_length=100)),
                ('DeviceDown4', models.CharField(max_length=100)),
                ('DeviceUp5', models.CharField(max_length=100)),
                ('DeviceDown5', models.CharField(max_length=100)),
                ('DeviceUp6', models.CharField(max_length=100)),
                ('DeviceDown6', models.CharField(max_length=100)),
                ('DeviceUp7', models.CharField(max_length=100)),
                ('DeviceDown7', models.CharField(max_length=100)),
                ('DeviceUp8', models.CharField(max_length=100)),
                ('DeviceDown8', models.CharField(max_length=100)),
            ],
        ),
    ]
