# Generated by Django 4.0.3 on 2022-06-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_devicestatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('IPId', models.AutoField(primary_key=True, serialize=False)),
                ('IP', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='RiskyDevice',
            fields=[
                ('DeviceId', models.AutoField(primary_key=True, serialize=False)),
                ('DeviceIP', models.CharField(max_length=100)),
                ('DeviceType', models.CharField(max_length=100)),
                ('DeviceActivityDesc', models.CharField(max_length=100)),
                ('DevicePriority', models.IntegerField()),
            ],
        ),
    ]
